export const
	{	assign,
		defineProperties: defines,
		defineProperty: define,
		entries,
		getOwnPropertyDescriptor: property,
		getOwnPropertyDescriptors: properties,
		getOwnPropertyNames: names,
		getOwnPropertySymbols: symbols,
		hasOwn: has,
		keys,
		fromEntries: object,
		values,

		create,
		freeze,
		preventExtensions,
		getPrototypeOf: protoOf,
		seal,
		is,
		isExtensible,
		isFrozen,
		isSealed } = Object,
	groupBy = ( a, f ) => a.reduce( ( o, i ) => ( ( o[ f( i ) ] ??= [] ).push( i ), o ), {} );
