export const {
	assign,
	create,
	defineProperties,
	defineProperty,
	entries,
	freeze,
	fromEntries,
	getOwnPropertyDescriptor,
	getOwnPropertyDescriptors,
	getOwnPropertyNames,
	getOwnPropertySymbols,
	getPrototypeOf,
	groupBy = ( a, f ) => a.reduce( ( o, i ) => ( ( o[ f( i ) ] ??= [] ).push( i ), o ), {} ),
	hasOwn,
	is,
	isExtensible,
	isFrozen,
	isSealed,
	keys,
	preventExtensions,
	seal,
	values,
} = Object;
